spring:
  application.name: hystrix-terbine-server
server:
  port: 8770
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig: default   
  appConfig: one-service
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.46:8761/eureka/